[target.thumbv7em-none-eabihf]
runner = "arm-none-eabi-gdb"
rustflags = [
    "-C", "link-arg=-Tlink.x",
    "-C", "link-arg=-Tmemory.x",
    "-C", "link-arg=-Tbootloader.x",
]

[build]
target = "thumbv7em-none-eabihf" 
